owner: Ogitay023
repo: status

sites:
  - name: ProfStriker
    url: https://profstriker.com

status-website:
  cname: status.profstriker.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ProfStriker Status
  introTitle: "**ProfStriker** servis durumu"
  introMessage: Tüm servislerin anlık durumunu buradan takip edebilirsiniz.
  navbar:
    - title: Status
      href: /
    - title: ProfStriker
      href: https://profstriker.com
